language: php
php:
  - 7.0
  - 7.3
# before_script:
#   - mysql -u root -e 'CREATE DATABASE testbase;'
#   - mysql -u root testbase < tests/testbase.sql
install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - nvm install 5.10.1

# Testing the app (see phpunit.xml) for configs, generating Code Coverage report
script:
#- composer test -- --coverage-clover=coverage.xml
- vendor/myvendor/mypackage/vendor/phpunit/phpunit/phpunit vendor/myvendor/mypackage/Tests/ --coverage-clover=coverage.xml

# You can delete the cache using travis-ci web interface
cache:
  directories:
  - $HOME/.composer/cache
