language: php
php:
  - 6.0
  - 7.3
  - hhvm

services:
  - mysql
before_install:
  - mysql -u root --password="" < travis_db_setup.sql

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - nvm install 5.10.1

# Testing the app (see phpunit.xml) for configs, generating Code Coverage report
script:
  #- phpunit --configuration phpunit_$DB.xml --coverage-text
  - composer test -- --coverage-clover=coverage.xml

# Delete the cache, after each environment test run
cache:
  directories:
  - $HOME/.composer/cache

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
 allow_failures:
   - php: 6.0
   - php: hhvm
 fast_finish: true

# Email notifications with the build results, this does can also be an IRC channel (I have seen)
notifications:
    on_success: never
    on_failure: always
    email: runehattmann@gmail.com
